---
title: "Subletting Leases"
output: html_document
date: '2022-08-03'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lease Subletting

## Who this page is for:
- Current MBAn students wishing to sublet their current leases to future MBAn studets
- Prospective and admitted MBAn students wanting to find housing for the former or latter part of their experience

## 1.1 You Want to Sublet Your Lease
So, you want to sublet your lease, but have had trouble finding someone. Great! We have taken the pain out of this process by connecting you with future MBAn students hungry to find a place to stay for a few months before their lease starts. To get started, just fill out this form. Interested students will be able to see all of this information and will contact you if they are interested. 

Form: https://docs.google.com/forms/d/e/1FAIpQLSfd5a1n3rtsh2xlqPA1M3tiaQFIl-nXuANBcQ9awZvN5U2sag/viewform

## 1.2 You Need a Place to Stay
Your lease doesn't start until August, so you need a place to stay for the summer. Or, your lease ends early and you need a place to stay for those last few month of the MBAn program. No problem! In the Google Sheet below, you will find a list of current MBAn students wishing to sublet their lease. Plenty of information about the properties is included in this document, but if you need more info, don't hesitate to reach out--contact information is provided. Happy shopping!

Sheet: https://docs.google.com/spreadsheets/d/1nCS9Tw-RBSAceeZNXqH_YfsoTt1rkVl-x5Z3lqS9AoQ/edit?resourcekey#gid=536291696
